pipeline {
    agent any
    parameters {
        choice(choices: ["TEST","QA","DEV","PROD"], description: "Enable dervice?", name: "deployEnv")
    }
    stages {
        stage("build job") {
            steps{
                echo "Choice is set to: ${params.deployEnv}"
                 }
        }
    }
}
    